## Example Notebook

In [13]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors

### Mentor Data

In [14]:
mentor_data = pd.DataFrame([
    {
        "Name": "Tom",
        "Python": 1,
        "HTML": 0,
        "CSS": 0,
        "JavaScript": 0,
    },
    {
        "Name": "Nick",
        "Python": 0,
        "HTML": 1,
        "CSS": 1,
        "JavaScript": 1,
    },
    {
        "Name": "Juli",
        "Python": 1,
        "HTML": 1,
        "CSS": 1,
        "JavaScript": 1,
    },
])
mentor_data

   Name  Python  HTML  CSS  JavaScript
0   Tom       1     0    0           0
1  Nick       0     1    1           1
2  Juli       1     1    1           1

### Mentee Data

In [15]:
mentee_data = pd.DataFrame([
    {
        "Name": "Adam",
        "Python": 0,
        "HTML": 1,
        "CSS": 1,
        "JavaScript": 1,
    },
    {
        "Name": "Brad",
        "Python": 1,
        "HTML": 0,
        "CSS": 0,
        "JavaScript": 0,
    },
    {
        "Name": "Lucy",
        "Python": 1,
        "HTML": 1,
        "CSS": 1,
        "JavaScript": 1,
    },
])
mentee_data

   Name  Python  HTML  CSS  JavaScript
0  Adam       0     1    1           1
1  Brad       1     0    0           0
2  Lucy       1     1    1           1

## Nearest Neighbors Model

In [16]:
model = NearestNeighbors(n_neighbors=1, algorithm="brute")
model.fit(mentor_data.drop(columns=["Name"]))

NearestNeighbors(algorithm='brute', n_neighbors=1)

### Find Matches

In [17]:
matches = model.kneighbors(mentee_data.drop(columns=["Name"]), return_distance=False)
matches_data = pd.DataFrame(matches, columns=["Mentor"])
matches_data.index.names = ["Mentee"]
matches_data = matches_data.reset_index()
matches_data

   Mentee  Mentor
0       0       1
1       1       0
2       2       2

In [18]:
def mentor_lookup(idx):
    return mentor_data.iloc[idx]["Name"]

In [19]:
def mentee_lookup(idx):
    return mentee_data.iloc[idx]["Name"]

In [20]:
from pandas import DataFrame

In [21]:
def lookup(idx: int, data: DataFrame):
    return data.iloc[idx]["Name"]

In [22]:
matches_data["Mentee"] = matches_data["Mentee"].apply(mentee_lookup)
matches_data["Mentor"] = matches_data["Mentor"].apply(mentor_lookup)
matches_data

  Mentee Mentor
0   Adam   Nick
1   Brad    Tom
2   Lucy   Juli